version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
      - "/modules/jenkins"
      - "/modules/perforce/helix-authentication-service"
      - "/modules/perforce/helix-core"
      - "/modules/perforce/helix-swarm"
      - "/samples/simple-build-pipeline"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
