version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
      - "/modules/jenkins"
      - "/modules/perforce"
      - "/modules/perforce/modules/p4-auth"
      - "/modules/perforce/modules/p4-server"
      - "/modules/perforce/modules/p4-code-review"
      - "/modules/teamcity"
      - "/modules/unreal/unreal-cloud-ddc/unreal-cloud-ddc-intra-cluster"
      - "/modules/unreal/unreal-cloud-ddc/unreal-cloud-ddc-infra"
      - "/modules/unreal/horde"
      - "/samples/simple-build-pipeline"
      - "/samples/unreal-cloud-ddc-single-region"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      aws-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/aws"
      awscc-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/awscc"
      random-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/random"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
