version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      aws-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/aws"
      awscc-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/awscc"
      random-provider:
        applies-to: version-updates
        patterns:
          - "hashicorp/random"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    schedule:
      interval: "daily"
