change-template: "* $TITLE (#$NUMBER) by @$AUTHOR"
categories:
  - title: "⚡ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🌟New features and non-breaking changes"
    labels:
      - "feature"
  - title: "📜 Documentation updates"
    labels:
      - "documentation"
  - title: "🐛 Bug and hot fixes"
    labels:
      - "bug"
      - "fix"
  - title: "🚒 Deprecations"
    labels:
      - "deprecated"
  - title: "🔧 Maintenance"
    labels:
      - "internal"
      - "dependencies"
exclude-labels:
  - "skip-changelog"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  ## Summary

  **[Human readable summary of changes]**

  ## Changes

  $CHANGES

  ## This release was made possible by the following contributors:

  $CONTRIBUTORS
