blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aws-games/cloud-game-development-toolkit/discussions
    about: Ask a question about the Cloud Game Development Toolkit
