blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aws-games/cloud-game-development-toolkit/discussions/new/choose
    about: Ask a question about the Cloud Game Development Toolkit