name: Feature request
description: Suggest an idea for Cloud Game Development Toolkit
title: "Feature request: TITLE"
labels: ["feature-request", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an idea for Cloud Game Development Toolkit.
        *Note*: If you find a feature request valuable, please react with 👍 and your use case to help us understand customer demand.
  - type: textarea
    id: problem
    attributes:
      label: Use case
      description: Please help us understand your use case or problem you're facing
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Solution/User Experience
      description: Please share what a good solution would look like to this use case
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Please describe what alternative solutions to this use case, if any
    validations:
      required: false