name: Maintenance
description: Suggest an activity to help address governance and anything internal
title: "Maintenance: TITLE"
labels: ["triage", "maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an idea for Cloud Game Development Toolkit.
        *Note*: If you find an issue valuable, please react with 👍 and your use case to help us understand customer demand.
  - type: textarea
    id: importance
    attributes:
      label: Why is this needed?
      description: Please help us understand the value so we can prioritize it accordingly
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Which area does this relate to?
      multiple: true
      options:
        - Governance and Project Management
        - CI/GitHub Actions
        - Other
  - type: textarea
    id: suggestion
    attributes:
      label: Solution
      description: If available, please share what a good solution would look like
    validations:
      required: false