apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ddc-compute
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: ddc-nodeclass
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: eks.amazonaws.com/instance-local-nvme
          operator: Gt
          values: ["100"]
      terminationGracePeriod: 24h0m0s
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized