branch: main
compact: true
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
output: cli
quiet: true
soft-fail-on:
  - CKV_GHA_7
skip-framework:
  - dockerfile
  - secrets
soft-fail: false
