formatter: markdown table
sections:
  show:
    - header
    - requirements
    - inputs
    - providers
    - modules
    - resources
    - footer
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sort:
  enabled: true
  by: required
