formatter: markdown table
sort:
  enabled: true
  by: required
output:
  file: README.md
  mode: inject
  template: |-
    <!-- markdownlint-disable -->
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
    <!-- markdownlint-enable -->
