# Packer template locations relative to ./packer directory
packer_templates:
  - file_name: './build-agents/linux/amazon-linux-2023-x86_64.pkr.hcl'             # Amazon Linux 2023 Jenkins Builder (x86)
  - file_name: './build-agents/linux/amazon-linux-2023-arm64.pkr.hcl'              # Amazon Linux 2023 Jenkins Builder (ARM)
  - file_name: './build-agents/linux/ubuntu-jammy-22.04-amd64-server.pkr.hcl'      # Ubuntu 22.04 LTS Jenkins Builder (x86)
  - file_name: './build-agents/linux/ubuntu-jammy-22.04-arm64-server.pkr.hcl'      # Ubuntu 22.04 LTS Jenkins Builder (ARM)