# Packer template locations relative to ./packer directory
packer_templates:
  - name: 'Amazon Linux 2023 Jenkins Builder (x86)'
    path: './build-agents/linux/'
    file_name: 'amazon-linux-2023-x86_64.pkr.hcl'
  - name: 'Amazon Linux 2023 Jenkins Builder (ARM)'
    path: './build-agents/linux/'
    file_name: 'amazon-linux-2023-arm64.pkr.hcl' 
  - name: 'Ubuntu 22.04 LTS Jenkins Builder (x86)'
    path: './build-agents/linux/'
    file_name: 'ubuntu-jammy-22.04-amd64-server.pkr.hcl'
  - name: 'Ubuntu 22.04 LTS Jenkins Builder (ARM)'
    path: './build-agents/linux/'
    file_name: 'ubuntu-jammy-22.04-arm64-server.pkr.hcl'