name: Auto Release

# Trigger workflow twice a month
on:
  #  schedule:
  #    - cron: "0 0 1,15 * *"
  workflow_dispatch:

permissions:
  actions: write
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  pages: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  tag-latest-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Get Semantic Version
        run: |
          IFS='.' read -r VERSION_MAJOR VERSION_MINOR VERSION_PATCH <<< ${{ vars.SEMANTIC_VERSION }}
          NEW_VERSION=v$VERSION_MAJOR.$VERSION_MINOR.$(($VERSION_PATCH+1))
      - name: checkout-latest
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          fetch-depth: 0
      - name: Setup Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: tag-version
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
      - name: tag-latest
        run: |
          git tag -f -a latest -m "Latest release"
          git push -f origin latest
      - name: create-release
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5
        with:
          tag: ${{ env.NEW_VERSION }}
          name: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: edit-publish-release
        run: |
          # Edit release content
          gh release edit ${{ inputs.release-version }} \
            --latest \
            --draft=false
      - name: update-repository-variable
        run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/gabebatista/cloud-game-development-toolkit/actions/variables/SEMANTIC_VERSION \
          -f "name=SEMANTIC_VERSION" -f "value=${{ env.NEW_VERSION }}"
