name: Update Changelog
on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action every day at midnight
  workflow_dispatch: # If we need to run the action manually
permissions:
  contents: read
jobs:
  update-changelog:
    if: github.repository == 'aws-games/cloud-game-development-toolkit'
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent race-condition and inconsistencies with changelog push
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      with:
        fetch-depth: 0
    - name: Update Changelog
      run: docker run --rm -v $(pwd):/workdir quay.io/git-chglog/git-chglog -o CHANGELOG.md
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git checkout -b changelog-update
        git add .
        git commit -m "Update Changelog"
        git push origin changelog-update
        echo $GH_TOKEN | gh auth login --with-token
        gh pr create --title chore: update changelog" --body "This is an auto-generated PR to update the changelog." --base main --head changelog-update --repo ${{ github.repository }} --confirm
