name: Checkov
on:
  pull_request:
      paths:
        - 'modules/**'
        - 'samples/**'
        - '.github/**'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@4b38516b47b2df46475d84383f9aa2c8ef912aae # v12.3087.0
        with:
          output_format: sarif
          output_file_path: results.sarif
          config_file: .config/.checkov.yml
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        if: success() || failure()
        with:
          sarif_file: results.sarif
