name: Jenkins Deployment Test

env:
  TF_VAR_fully_qualified_domain_name: ${{ secrets.CI_FULLY_QUALIFIED_DOMAIN_NAME }}

# push on: PR when jenkin's files are changed
on:
  push: # change to pull_request before publish
    paths:
      - 'modules/jenkins/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  prep:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: home/runner/work

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

  plan:
    needs: [ prep ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/jenkins/examples/complete
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: Terraform init and validate
        run: |
          terraform init

      # Save output as file and pass to apply step
      - name: Terraform plan
        run: |
          terraform plan


  deploy:
    needs: [ plan ]
    environment: jenkins-test-environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/jenkins/examples/complete
    steps:
      # Write output file as comment in triggering PR
      # - name: Manual Approval in Triggering PR

      # Run apply
      - name: Terraform apply
        run: |
          terraform apply

  destroy:
    needs: [ deploy ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/jenkins/examples/complete
    steps:
      - name: Terraform Destroy
        run: |
          terraform destroy
