name: Packer Daily Builds
on:
  schedule:
    - cron:  '0 0 * * *'  # Run every day at midnight
  workflow_dispatch: # Manually trigger the workflow
permissions:
  id-token: write
  contents: read
env:
  GITHUB_BRANCH: main
jobs:
  get-packer-templates: # Retrieve the Packer templates from the config file and build a matrix of them to run parallel jobs
    if: github.repository == 'aws-games/cloud-game-development-toolkit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          ref: ${{ env.GITHUB_BRANCH }}
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Get Packer templates
        id: packer-templates-matrix
        working-directory: ./assets/packer/
        run: |
          MATRIX_JSON=$(yq e -j '.packer_templates[] | {"file_name": .file_name, "dir": .dir, "description": .description}' .config.yml | jq -s 'reduce .[] as $item ({}; . + {($item.file_name): $item})' | jq -c '[.[]]')
          echo "::set-output name=matrix::${MATRIX_JSON}"
          echo "MATRIX_JSON: ${MATRIX_JSON}"
    outputs:
      matrix: ${{ steps.packer-templates-matrix.outputs.matrix }}
  run-packer-builds:
    if: github.repository == 'aws-games/cloud-game-development-toolkit'
    needs: get-packer-templates
    strategy:
      matrix: 
        include: ${{fromJson(needs.get-packer-templates.outputs.matrix)}}
    continue-on-error: true
    environment: aws-ci
    runs-on: ubuntu-latest
    steps:
    - name: 'Build Packer template - ${{ matrix.file_name }}
      uses: ./github/workflows/packer-build.yml
      with:
        packer_template_file_name: ${{ matrix.file_name }}
        packer_template_dir: ${{ matrix.dir }}
        packer_template_description: ${{ matrix.description }}
        branch: ${{ env.GITHUB_BRANCH }}