name: pre-commit

on:
  pull_request:
<<<<<<< HEAD
    branches: [main]
=======
>>>>>>> 3dcaf06 (adding pre-commit hooks for GH actions (#84))
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
<<<<<<< HEAD
    - uses: bridgecrewio/checkov-action@master
=======
>>>>>>> 3dcaf06 (adding pre-commit hooks for GH actions (#84))
    - uses: pre-commit/action@v3.0.1