# Runs security scans 

name: Security
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy.yml
    secrets: inherit
  codeql-analysis:
    uses: ./.github/workflows/codeql-analysis.yml
    secrets: inherit
